"""create document indexing jobs

Revision ID: 1012f991b595
Revises: b51a5d4764ca
Create Date: 2026-09-30 16:21:14.582422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1012f991b595'
down_revision: Union[str, Sequence[str], None] = 'b51a5d4764ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_indexing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('staged_storage_uri', sa.Text(), nullable=False),
    sa.Column('candidate_file_name', sa.String(length=500), nullable=False),
    sa.Column('candidate_mime_type', sa.String(length=100), nullable=False),
    sa.Column('candidate_content_hash', sa.String(length=64), nullable=False),
    sa.Column('target_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('indexed_chunk_count', sa.Integer(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed')", name='ck_indexing_jobs_status'),
    sa.CheckConstraint('attempt_count <= max_attempts', name='ck_indexing_jobs_attempt_limit'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_indexing_jobs_attempt_count'),
    sa.CheckConstraint('indexed_chunk_count IS NULL OR indexed_chunk_count >= 0', name='ck_indexing_jobs_chunk_count'),
    sa.CheckConstraint('max_attempts >= 1', name='ck_indexing_jobs_max_attempts'),
    sa.CheckConstraint('target_version >= 1', name='ck_indexing_jobs_target_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'knowledge_base_id', 'document_id'], ['documents.tenant_id', 'documents.knowledge_base_id', 'documents.id'], name='fk_indexing_jobs_document', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'requested_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_indexing_jobs_requested_by_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_indexing_jobs_claim', 'document_indexing_jobs', ['status', 'available_at', 'created_at'], unique=False)
    op.create_index('ix_indexing_jobs_scope_document', 'document_indexing_jobs', ['tenant_id', 'knowledge_base_id', 'document_id', 'created_at'], unique=False)
    op.create_index('uq_indexing_jobs_active_document', 'document_indexing_jobs', ['tenant_id', 'knowledge_base_id', 'document_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"), sqlite_where=sa.text("status IN ('queued', 'running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_indexing_jobs_active_document', table_name='document_indexing_jobs', postgresql_where=sa.text("status IN ('queued', 'running')"), sqlite_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index('ix_indexing_jobs_scope_document', table_name='document_indexing_jobs')
    op.drop_index('ix_indexing_jobs_claim', table_name='document_indexing_jobs')
    op.drop_table('document_indexing_jobs')
    # ### end Alembic commands ###
