"""create tenant permission tables

Revision ID: 301e7f0d190f
Revises: 
Create Date: 2026-09-26 19:47:14.420117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301e7f0d190f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled')", name='ck_tenants_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled')", name='ck_departments_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_departments_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_departments_tenant_name')
    )
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled')", name='ck_knowledge_bases_status'),
    sa.CheckConstraint("visibility IN ('company', 'restricted')", name='ck_knowledge_bases_visibility'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_knowledge_bases_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_knowledge_bases_tenant_name')
    )
    op.create_index('ix_knowledge_bases_tenant_status', 'knowledge_bases', ['tenant_id', 'status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('external_subject', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled')", name='ck_users_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_subject', name='uq_users_tenant_external_subject'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_users_tenant_id')
    )
    op.create_index('ix_users_tenant_status', 'users', ['tenant_id', 'status'], unique=False)
    op.create_table('department_memberships',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('member', 'manager')", name='ck_department_memberships_role'),
    sa.ForeignKeyConstraint(['tenant_id', 'department_id'], ['departments.tenant_id', 'departments.id'], name='fk_memberships_department', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['users.tenant_id', 'users.id'], name='fk_memberships_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'department_id', 'user_id')
    )
    op.create_index('ix_memberships_tenant_user', 'department_memberships', ['tenant_id', 'user_id'], unique=False)
    op.create_table('knowledge_base_department_grants',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("permission IN ('viewer', 'editor', 'admin')", name='ck_kb_department_grants_permission'),
    sa.ForeignKeyConstraint(['tenant_id', 'department_id'], ['departments.tenant_id', 'departments.id'], name='fk_kb_department_grants_department', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'knowledge_base_id'], ['knowledge_bases.tenant_id', 'knowledge_bases.id'], name='fk_kb_department_grants_kb', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'knowledge_base_id', 'department_id')
    )
    op.create_index('ix_kb_department_grants_department', 'knowledge_base_department_grants', ['tenant_id', 'department_id'], unique=False)
    op.create_table('knowledge_base_user_grants',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("permission IN ('viewer', 'editor', 'admin')", name='ck_kb_user_grants_permission'),
    sa.ForeignKeyConstraint(['tenant_id', 'knowledge_base_id'], ['knowledge_bases.tenant_id', 'knowledge_bases.id'], name='fk_kb_user_grants_kb', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'user_id'], ['users.tenant_id', 'users.id'], name='fk_kb_user_grants_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'knowledge_base_id', 'user_id')
    )
    op.create_index('ix_kb_user_grants_user', 'knowledge_base_user_grants', ['tenant_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kb_user_grants_user', table_name='knowledge_base_user_grants')
    op.drop_table('knowledge_base_user_grants')
    op.drop_index('ix_kb_department_grants_department', table_name='knowledge_base_department_grants')
    op.drop_table('knowledge_base_department_grants')
    op.drop_index('ix_memberships_tenant_user', table_name='department_memberships')
    op.drop_table('department_memberships')
    op.drop_index('ix_users_tenant_status', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_knowledge_bases_tenant_status', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_table('departments')
    op.drop_table('tenants')
    # ### end Alembic commands ###
