"""create document vector tables

Revision ID: b51a5d4764ca
Revises: 57b2cab16960
Create Date: 2026-09-27 18:00:38.449455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = 'b51a5d4764ca'
down_revision: Union[str, Sequence[str], None] = '57b2cab16960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'indexing', 'ready', 'failed')", name='ck_documents_status'),
    sa.CheckConstraint('version >= 1', name='ck_documents_version'),
    sa.ForeignKeyConstraint(['tenant_id', 'created_by_user_id'], ['users.tenant_id', 'users.id'], name='fk_documents_created_by_user'),
    sa.ForeignKeyConstraint(['tenant_id', 'knowledge_base_id'], ['knowledge_bases.tenant_id', 'knowledge_bases.id'], name='fk_documents_knowledge_base', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'knowledge_base_id', 'id', name='uq_documents_tenant_kb_id'),
    sa.UniqueConstraint('tenant_id', 'knowledge_base_id', 'source_id', name='uq_documents_tenant_kb_source')
    )
    op.create_index('ix_documents_tenant_kb_status', 'documents', ['tenant_id', 'knowledge_base_id', 'status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('chunking_version', sa.String(length=50), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column("embedding",VECTOR(1024),nullable=False,),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='ck_document_chunks_index'),
    sa.ForeignKeyConstraint(['tenant_id', 'knowledge_base_id', 'document_id'], ['documents.tenant_id', 'documents.knowledge_base_id', 'documents.id'], name='fk_document_chunks_document', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'knowledge_base_id', 'document_id', 'chunk_index', name='uq_document_chunks_position')
    )
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_document_chunks_scope_document', 'document_chunks', ['tenant_id', 'knowledge_base_id', 'document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_scope_document', table_name='document_chunks')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_chunks')
    op.drop_index('ix_documents_tenant_kb_status', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
